In [2]:
import pandas as pd
import numpy as np

#load training data
titanic = pd.read_csv('titanic.csv')
from sklearn.model_selection import train_test_split


In [3]:
titanic[:5]
titanic.isnull().sum()

PassengerId       0
Survived        418
Pclass            0
Name              0
Sex               0
Age             263
SibSp             0
Parch             0
Ticket            0
Fare              1
Cabin          1014
Embarked          2
WikiId            5
Name_wiki         5
Age_wiki          7
Hometown          5
Boarded           5
Destination       5
Lifeboat        807
Body           1179
Class             5
dtype: int64

In [4]:
impute_value1 = titanic['Survived'].median()
titanic['Survived'] = titanic['Survived'].fillna(impute_value1)

impute_value12 = titanic['Fare'].median()
titanic['Fare'] = titanic['Fare'].fillna(impute_value1)

titanic.isnull().sum()

PassengerId       0
Survived          0
Pclass            0
Name              0
Sex               0
Age             263
SibSp             0
Parch             0
Ticket            0
Fare              0
Cabin          1014
Embarked          2
WikiId            5
Name_wiki         5
Age_wiki          7
Hometown          5
Boarded           5
Destination       5
Lifeboat        807
Body           1179
Class             5
dtype: int64

In [5]:
#As we can see that the above columns have many missing values, filling the missing values
impute_value = titanic['Age'].median()
titanic['Age'] = titanic['Age'].fillna(impute_value)


In [6]:
titanic['IsFemale'] = (titanic['Sex'] == 'female').astype(int)

In [7]:
predictors = ['Pclass', 'IsFemale', 'Age']
X = titanic[predictors].values
X.shape
Y = titanic['Survived']
Y.shape
X[:5]

array([[ 3.,  0., 22.],
       [ 1.,  1., 38.],
       [ 3.,  1., 26.],
       [ 1.,  1., 35.],
       [ 3.,  0., 35.]])

In [8]:
X[:5]

array([[ 3.,  0., 22.],
       [ 1.,  1., 38.],
       [ 3.,  1., 26.],
       [ 1.,  1., 35.],
       [ 3.,  0., 35.]])

In [9]:
X_train, X_test, y_train , y_test = train_test_split(X, Y,random_state=42)

In [10]:
X_train[:5]

array([[ 2.,  1., 29.],
       [ 3.,  1., 43.],
       [ 1.,  1., 26.],
       [ 3.,  0., 33.],
       [ 1.,  0., 28.]])

In [11]:
y_train[:5]
np.isfinite(X)


array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       ...,
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [12]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [13]:
model.score(X_train,y_train)

0.7910295616717635

In [14]:
model.score(X_test,y_test)

0.75

In [15]:
#lets tune the value of C
model1 = LogisticRegression(C=10)
model1.fit(X_train,y_train)

LogisticRegression(C=10, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [16]:
#lets try to change the data
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(X_train)
X_train_scaled = scaler.transform(X_train)

In [17]:
X_test_scaled = scaler.transform(X_test)

In [18]:
model = LogisticRegression()
model.fit(X_train_scaled,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [19]:
model.score(X_train_scaled,y_train)

0.7910295616717635

In [20]:
model.score(X_test_scaled,y_test)

0.75

In [21]:
#no improvement has seen lets check with StandardScaler
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)
model.fit(X_train_scaled,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [22]:
model.score(X_train_scaled,y_train)

0.7910295616717635

In [23]:
model.score(X_test_scaled,y_test)

0.75

In [24]:
#no improvement has seen lets change the number of features as predictors
predictors = ['Pclass', 'IsFemale', 'Age', 'Fare']
X = titanic[predictors].values
X.shape

(1309, 4)

In [25]:
X_train, X_test, y_train , y_test = train_test_split(X, Y,random_state=42)

In [26]:
X_test[:5]

array([[ 3.   ,  0.   , 28.   ,  8.05 ],
       [ 1.   ,  0.   , 42.   , 26.55 ],
       [ 3.   ,  0.   , 28.   ,  7.775],
       [ 2.   ,  0.   , 39.   , 13.   ],
       [ 3.   ,  1.   , 28.   ,  7.75 ]])

In [27]:
model = LogisticRegression()
model.fit(X_train,y_train)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [28]:
model.score(X_train,y_train)

0.7930682976554536

In [29]:
model.score(X_test,y_test)

0.7530487804878049

In [30]:
#there is a bit increase in score on test set 
#lets change equalize the data set using standard scaler
scaler = StandardScaler()
scaler.fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)
model.fit(X_train_scaled,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [31]:
model.score(X_test_scaled,y_test)

0.7530487804878049

In [32]:
#no improvement further lets try to increase it to two more feature
predictors = ['Pclass', 'IsFemale', 'Age', 'Fare', 'SibSp', 'Parch']
X = titanic[predictors].values
X.shape


(1309, 6)

In [33]:
X_train, X_test, y_train , y_test = train_test_split(X, Y,random_state=42)

In [34]:
model.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [41]:
model.score(X_train,y_train)

0.7971457696228338

In [42]:
model.score(X_test,y_test)

0.7560975609756098

In [43]:
from sklearn.neighbors import KNeighborsClassifier

In [44]:
knn = KNeighborsClassifier()

In [45]:
knn.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [46]:
knn.score(X_train,y_train)

0.8093781855249745

In [47]:
knn.score(X_test,y_test)

0.7286585365853658

In [41]:
from sklearn.tree import DecisionTreeClassifier

In [42]:
dtc = DecisionTreeClassifier()

In [43]:
dtc.fit(X_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [44]:
dtc.score(X_train,y_train)

0.981651376146789

In [45]:
dtc.score(X_test,y_test)

0.7103658536585366

In [ ]:
#No improvement!

In [48]:

#lets try to change the random state to 100 in logistic regresion
X_train, X_test, y_train , y_test = train_test_split(X, Y,random_state=100)

In [165]:
model.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [167]:
model.score(X_train,y_train)

0.7889908256880734

In [168]:
model.score(X_test,y_test)

0.7896341463414634

In [204]:
#Now we can see a 3% improvement lets continue changing random state value
X_train, X_test, y_train , y_test = train_test_split(X, Y,random_state=300)

In [176]:
model.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [206]:
model.score(X_train,y_train)

0.7828746177370031

In [205]:
model.score(X_test,y_test)

0.8079268292682927

In [498]:
#Thats great! improvement has happened on the test data lets now move on to the other classifier
from sklearn.svm import SVC 
svm = SVC(kernel='rbf',C=100,gamma=0.8)
svm.fit(X_train,y_train)

SVC(C=100, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.8, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [499]:
svm.score(X_train,y_train)

0.9612640163098879

In [500]:
svm.score(X_test,y_test)

0.698170731707317

In [501]:
#Lets try to change the data using StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)
model.fit(X_train_scaled,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [502]:
svm.fit(X_train_scaled,y_train)

SVC(C=100, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.8, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [503]:
scaler = MinMaxScaler()
scaler.fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [504]:
svm.fit(X_train_scaled,y_train)

SVC(C=100, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.8, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [505]:
svm.score(X_train_scaled,y_train)

0.7981651376146789

In [506]:
svm.score(X_test_scaled,y_test)

0.8201219512195121

In [507]:
#We can clearly see the improvement using MinMaxScaler
#lets try to use principle component analysis
from sklearn.decomposition import PCA
pca = PCA(n_components=2)
pca.fit(X_train)

PCA(copy=True, iterated_power='auto', n_components=2, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)

In [508]:
X_pca = pca.transform(X_train_scaled)
X_pca1 = pca.transform(X_test_scaled)

In [509]:
svm.fit(X_pca,y_train)

SVC(C=100, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.8, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [513]:
svm.fit(X_pca,y_train)

SVC(C=100, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.8, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [511]:
svm.score(X_pca1,y_test)

0.7408536585365854

In [512]:
svm.score(X_pca1,y_test)

0.7408536585365854

In [278]:
scaler = StandardScaler()
scaler.fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [279]:
X_pca = pca.transform(X_train_scaled)
X_pca1 = pca.transform(X_test_scaled)
svm.fit(X_pca,y_train)

SVC(C=300, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [280]:
svm.score(X_pca1,y_test)

0.7408536585365854

In [323]:
#as we can see from above that pca is not giving good results as only 6 input features are present
X_train, X_test, y_train , y_test = train_test_split(X, Y,random_state=0)
#Lets go to Kmeans clustering classifier
from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters=2)
kmeans.fit(X_train)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
       n_clusters=2, n_init=10, n_jobs=None, precompute_distances='auto',
       random_state=None, tol=0.0001, verbose=0)

In [590]:
#Lets try to use our final best tool Random Forests
X_train, X_test, y_train , y_test = train_test_split(X, Y,random_state=300)
from sklearn.ensemble import RandomForestClassifier
forest = RandomForestClassifier(n_estimators=100,max_depth=3,random_state=0,max_features=4)
forest.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=3, max_features=4,
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [593]:
forest.score(X_train,y_train)

0.7930682976554536

In [428]:
#Lets scale the data and check
scaler = StandardScaler()
scaler.fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [429]:
forest.fit(X_train_scaled,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=3, max_features=4,
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [430]:
forest.score(X_test_scaled,y_test)

0.8201219512195121

In [431]:
#Lets use MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [432]:
forest.fit(X_train_scaled,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=3, max_features=4,
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [433]:
forest.score(X_train_scaled,y_train)

0.799184505606524

In [434]:
forest.score(X_test_scaled,y_test)

0.8201219512195121

In [361]:
#Lets try with Gradient Boosting Classifier
from sklearn.ensemble import GradientBoostingClassifier

In [406]:
gbrt = GradientBoostingClassifier(random_state=300, max_depth=2)

In [407]:
gbrt.fit(X_train,y_train)

GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=2,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=100,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=300, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)

In [408]:
gbrt.score(X_train,y_train)

0.817533129459735

In [409]:
gbrt.score(X_test,y_test)

0.8140243902439024

In [401]:
gbrt.fit(X_train_scaled,y_train)

GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=2,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=100,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=500, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)

In [402]:
gbrt.score(X_train_scaled,y_train)

0.817533129459735

In [405]:
gbrt.score(X_test_scaled,y_test)

0.8140243902439024

In [533]:
#Not much improvement further lets try with neural
from sklearn.neural_network import MLPClassifier
mlp = MLPClassifier(max_iter=100, alpha=3,random_state=0)
mlp.fit(X_train,y_train)

MLPClassifier(activation='relu', alpha=3, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(100,), learning_rate='constant',
              learning_rate_init=0.001, max_fun=15000, max_iter=100,
              momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=0, shuffle=True, solver='adam',
              tol=0.0001, validation_fraction=0.1, verbose=False,
              warm_start=False)

In [534]:
mlp.score(X_train,y_train)

0.7767584097859327

In [535]:
mlp.score(X_test,y_test)

0.7896341463414634

In [538]:
#No improvement lets increase the number of features
titanic[:5]


PassengerId  Survived  Pclass  \
0            1       0.0       3   
1            2       1.0       1   
2            3       1.0       3   
3            4       1.0       1   
4            5       0.0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare  ... WikiId  \
0      0         A/5 21171   7.2500  ...  691.0   
1      0          PC 17599  71.2833  ...   90.0   
2      0  STON/O2. 3101282   7.9250  ...  865.0   
3      0            113803  53.1000  ...  127.0   
4      0            373450   8.0500  ...  627.0   

                                    Name_wiki  Age_wiki  \
0                     Braund, Mr. Owen Harris      22.0   
1  Cumings, Mrs. Florence Briggs (née Thayer)      35.0   
2                       Heikkinen, Miss Laina      26.0   
3          Futrelle, Mrs. Lily May (née Peel)      35.0   
4                    Allen, Mr. William Henry      35.0   

                             Hometown      Boarded  \
0          Bridgerule, Devon, England  Southampton   
1              New York, New York, US    Cherbourg   
2                  Jyväskylä, Finland  Southampton   
3         Scituate, Massachusetts, US  Southampton   
4  Birmingham, West Midlands, England  Southampton   

                               Destination Lifeboat Body Class IsFemale  
0  Qu'Appelle Valley, Saskatchewan, Canada      NaN  NaN   3.0        0  
1                   New York, New York, US        4  NaN   1.0        1  
2                            New York City      14?  NaN   3.0        1  
3              Scituate, Massachusetts, US        D  NaN   1.0        1  
4                            New York City      NaN  NaN   3.0        0  

[5 rows x 22 columns]

In [550]:
Titanic = titanic[['Pclass', 'IsFemale', 'Age', 'SibSp', 'Parch', 'Fare', 'Boarded']]

In [555]:
Titanic[:5]

Pclass  IsFemale   Age  SibSp  Parch     Fare      Boarded
0       3         0  22.0      1      0   7.2500  Southampton
1       1         1  38.0      1      0  71.2833    Cherbourg
2       3         1  26.0      0      0   7.9250  Southampton
3       1         1  35.0      1      0  53.1000  Southampton
4       3         0  35.0      0      0   8.0500  Southampton

In [569]:
Titanic_new = Titanic.fillna('Unknown')


In [572]:
data_dummies = pd.get_dummies(Titanic)
print("Features after get_dummies:\n", list(data_dummies.columns))

Features after get_dummies:
 ['Pclass', 'IsFemale', 'Age', 'SibSp', 'Parch', 'Fare', 'Boarded_Belfast', 'Boarded_Cherbourg', 'Boarded_Queenstown', 'Boarded_Southampton']


In [573]:
features=data_dummies.loc[:, 'Pclass':'Boarded_Southampton']

In [574]:
features

Pclass  IsFemale   Age  SibSp  Parch      Fare  Boarded_Belfast  \
0          3         0  22.0      1      0    7.2500                0   
1          1         1  38.0      1      0   71.2833                0   
2          3         1  26.0      0      0    7.9250                0   
3          1         1  35.0      1      0   53.1000                0   
4          3         0  35.0      0      0    8.0500                0   
...      ...       ...   ...    ...    ...       ...              ...   
1304       3         0  28.0      0      0    8.0500                0   
1305       1         1  39.0      0      0  108.9000                0   
1306       3         0  38.5      0      0    7.2500                0   
1307       3         0  28.0      0      0    8.0500                0   
1308       3         0  28.0      1      1   22.3583                0   

      Boarded_Cherbourg  Boarded_Queenstown  Boarded_Southampton  
0                     0                   0                    1  
1                     1                   0                    0  
2                     0                   0                    1  
3                     0                   0                    1  
4                     0                   0                    1  
...                 ...                 ...                  ...  
1304                  0                   0                    1  
1305                  1                   0                    0  
1306                  0                   0                    1  
1307                  0                   0                    1  
1308                  1                   0                    0  

[1309 rows x 10 columns]

In [575]:
X=features.values

In [578]:
X[:5]

array([[ 3.    ,  0.    , 22.    ,  1.    ,  0.    ,  7.25  ,  0.    ,
         0.    ,  0.    ,  1.    ],
       [ 1.    ,  1.    , 38.    ,  1.    ,  0.    , 71.2833,  0.    ,
         1.    ,  0.    ,  0.    ],
       [ 3.    ,  1.    , 26.    ,  0.    ,  0.    ,  7.925 ,  0.    ,
         0.    ,  0.    ,  1.    ],
       [ 1.    ,  1.    , 35.    ,  1.    ,  0.    , 53.1   ,  0.    ,
         0.    ,  0.    ,  1.    ],
       [ 3.    ,  0.    , 35.    ,  0.    ,  0.    ,  8.05  ,  0.    ,
         0.    ,  0.    ,  1.    ]])

In [579]:
X_train, X_test, y_train , y_test = train_test_split(X, Y,random_state=0)

In [580]:
X_train[:5]

array([[ 2.    ,  1.    , 30.    ,  0.    ,  0.    , 13.    ,  0.    ,
         0.    ,  0.    ,  1.    ],
       [ 3.    ,  0.    , 24.    ,  2.    ,  0.    , 24.15  ,  0.    ,
         0.    ,  0.    ,  1.    ],
       [ 3.    ,  1.    , 28.    ,  0.    ,  0.    ,  7.7875,  0.    ,
         0.    ,  1.    ,  0.    ],
       [ 3.    ,  1.    , 29.    ,  0.    ,  4.    , 21.075 ,  0.    ,
         0.    ,  0.    ,  1.    ],
       [ 3.    ,  1.    , 28.    ,  8.    ,  2.    , 69.55  ,  0.    ,
         0.    ,  0.    ,  1.    ]])

In [582]:
model.fit(X_train,y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [583]:
model.score(X_train,y_train)

0.7869520897043832

In [584]:
model.score(X_test,y_test)

0.7591463414634146

In [585]:
svm.fit(X_train,y_train)

SVC(C=100, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.8, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [586]:
svm.score(X_train,y_train)

0.9704383282364933

In [587]:
model.score(X_test,y_test)

0.7591463414634146